export default [
  {
    id: 24,
    name: "Sinsen friområde",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: null,
    location: null,
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 25,
    name: "Abildsø idrettspark",
    homePageLink: "http://www.abildso-il.no/",
    openingTime: null,
    closingTime: null,
    locationId: 12,
    location: {
      id: 12,
      latitude: "59.885101590881",
      longitude: "10.82200724375",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1187",
      address: "Smedbergveien 25",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 26,
    name: "Alna idrettspark",
    homePageLink: "http://www.furuset.no/",
    openingTime: null,
    closingTime: null,
    locationId: 13,
    location: {
      id: 13,
      latitude: "59.940610270093",
      longitude: "10.878200122652",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1081",
      address: "Professor Birkelands vei 28 d",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 27,
    name: "Ammerud idrettshall",
    homePageLink: "http://www.grei.no/?lbNavLoc=3",
    openingTime: null,
    closingTime: null,
    locationId: 14,
    location: {
      id: 14,
      latitude: "59.965113883908",
      longitude: "10.873675710937",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0958",
      address: "Ammerudveien 49",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 28,
    name: "Apalløkka idrettshall",
    homePageLink: "http://www.ammerudhandball.no",
    openingTime: null,
    closingTime: null,
    locationId: 15,
    location: {
      id: 15,
      latitude: "59.95948102",
      longitude: "10.864258716191",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0957",
      address: "Tjernveien 10",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 29,
    name: "Berg tennis",
    homePageLink: "http://www.bergtennis.no/",
    openingTime: null,
    closingTime: null,
    locationId: 16,
    location: {
      id: 16,
      latitude: "59.950854361146",
      longitude: "10.745754363867",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0870",
      address: "Irisveien 12",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 30,
    name: "Bergbanen",
    homePageLink:
      "http://kxweb.no/portal/theme/organization/main.do?siteId=403",
    openingTime: null,
    closingTime: null,
    locationId: 17,
    location: {
      id: 17,
      latitude: "59.950604978429",
      longitude: "10.738113392579",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0855",
      address: "Kaj Munks vei 7",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 31,
    name: "Bestum skole idrettshall",
    homePageLink: "https://www.ullern.no",
    openingTime: null,
    closingTime: null,
    locationId: 18,
    location: {
      id: 18,
      latitude: "59.924079714461",
      longitude: "10.654300681607",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0280",
      address: "Holgerslystveien 18",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 32,
    name: "Bislett stadion",
    homePageLink: "http://www.bislettstadion.no/",
    openingTime: null,
    closingTime: null,
    locationId: 19,
    location: {
      id: 19,
      latitude: "59.924089545302",
      longitude: "10.733992362373",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0168",
      address: "Bislettgata 1",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 33,
    name: "Bjølsenhallen",
    homePageLink: "http://sageneif.no/",
    openingTime: null,
    closingTime: null,
    locationId: 20,
    location: {
      id: 20,
      latitude: "59.943693177985",
      longitude: "10.760845203685",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0468",
      address: "Moldegata 1",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 34,
    name: "Bjølsenparken fotballbane",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 21,
    location: {
      id: 21,
      latitude: "59.939759",
      longitude: "10.756331",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0464",
      address: "Grimstadgata 30 J",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 35,
    name: "Bjørndal idrettspark",
    homePageLink: "http://www.bjorndal-if.no/",
    openingTime: null,
    closingTime: null,
    locationId: 22,
    location: {
      id: 22,
      latitude: "59.824254427586",
      longitude: "10.833363855971",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1271",
      address: "Seterbråtveien 4",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 36,
    name: "Bjørnholt idrettshall",
    homePageLink: "http://www.bjorndal-if.no/",
    openingTime: null,
    closingTime: null,
    locationId: 23,
    location: {
      id: 23,
      latitude: "59.834444743453",
      longitude: "10.835583560974",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1277",
      address: "Slimeveien 17",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 37,
    name: "Bjøråsen skoleidrettsplass",
    homePageLink: "http://fotball.romsas-il.no/",
    openingTime: null,
    closingTime: null,
    locationId: 24,
    location: {
      id: 24,
      latitude: "59.970834328422",
      longitude: "10.900122476151",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0972",
      address: "Sverre Iversens vei 37",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 38,
    name: "Brynbanen",
    homePageLink:
      "http://kxweb.no/portal/public/showContentCategory.do?id=948510249",
    openingTime: null,
    closingTime: null,
    locationId: 25,
    location: {
      id: 25,
      latitude: "59.915011",
      longitude: "10.824639",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0666",
      address: "Ole Deviks vei 10",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 39,
    name: "Bråten friområde",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 26,
    location: {
      id: 26,
      latitude: "59.904155",
      longitude: "10.849805",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0672",
      address: "Hellerudveien 63",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 40,
    name: "Bygger’n aktivitetspark",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 27,
    location: {
      id: 27,
      latitude: "59.949062",
      longitude: "10.92137",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0977",
      address: "Byggern Aktivitetspark",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 41,
    name: "Bøler idrettshall",
    homePageLink: "https://bolerif.no/",
    openingTime: null,
    closingTime: null,
    locationId: 28,
    location: {
      id: 28,
      latitude: "59.883751636285",
      longitude: "10.849274786268",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0620",
      address: "Utmarkveien 4",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 42,
    name: "Bøler idrettsplass",
    homePageLink:
      "http://kxweb.no/portal/theme/organization/main.do?siteId=447",
    openingTime: null,
    closingTime: null,
    locationId: 29,
    location: {
      id: 29,
      latitude: "59.884259",
      longitude: "10.84858",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0689",
      address: "General Ruges vei 45",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 43,
    name: "Caltexløkka",
    homePageLink: "http://www.ltfk.no",
    openingTime: null,
    closingTime: null,
    locationId: 30,
    location: {
      id: 30,
      latitude: "59.916476",
      longitude: "10.77813",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0563",
      address: "Finnmarkgata 27",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 44,
    name: "Disen idrettspark",
    homePageLink: "http://www.aarvoll.no/",
    openingTime: null,
    closingTime: null,
    locationId: 31,
    location: {
      id: 31,
      latitude: "59.948527",
      longitude: "10.821115",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0591",
      address: "Kildeveien",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 45,
    name: "Disen tennis",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 32,
    location: {
      id: 32,
      latitude: "59.941484503153",
      longitude: "10.798069603463",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0587",
      address: "Disenveien 53",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 46,
    name: "Dælenenga idrettsplass",
    homePageLink: "http://www.gruner.no/",
    openingTime: null,
    closingTime: null,
    locationId: 33,
    location: {
      id: 33,
      latitude: "59.926417",
      longitude: "10.764447",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0556",
      address: "Seilduksgata 30",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 47,
    name: "Ekeberg idrettspark",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 34,
    location: {
      id: 34,
      latitude: "59.894081",
      longitude: "10.77811",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1181",
      address: "Ekebergsletta",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 48,
    name: "Ellingsrud fleridrettshall",
    homePageLink: "http://www.ellingsrudhandball.no/",
    openingTime: null,
    closingTime: null,
    locationId: 35,
    location: {
      id: 35,
      latitude: "59.93297586529",
      longitude: "10.926201375225",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1065",
      address: "Karolinerveien 5",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 49,
    name: "Ellingsrud idrettspark",
    homePageLink: "http://ellingsrud-il-fotball.idrettenonline.no/p/11209/hjem",
    openingTime: null,
    closingTime: null,
    locationId: 36,
    location: {
      id: 36,
      latitude: null,
      longitude: null,
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1061",
      address: "Gamle Strømsvei 109",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 50,
    name: "Eltonveien park",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 37,
    location: {
      id: 37,
      latitude: "59.938998480258",
      longitude: "10.80056625473",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0856",
      address: "Eltonveien 5",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 51,
    name: "Engebråten idrettshall",
    homePageLink: "http://www.kjelsaas.no/",
    openingTime: null,
    closingTime: null,
    locationId: 38,
    location: {
      id: 38,
      latitude: "59.959751428687",
      longitude: "10.775631987308",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0493",
      address: "Kapellveien 120",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 52,
    name: "Fagerheim tennis",
    homePageLink: "http://fagerheimen.blogspot.no/",
    openingTime: null,
    closingTime: null,
    locationId: 39,
    location: {
      id: 39,
      latitude: "59.92994",
      longitude: "10.770129",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0569",
      address: "Mailundveien 19",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 53,
    name: "Fokus bordtennis",
    homePageLink: "http://www.fokusbtk.no/",
    openingTime: null,
    closingTime: null,
    locationId: 40,
    location: {
      id: 40,
      latitude: "59.900016152812",
      longitude: "10.812526020125",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0678",
      address: "Traktorveien 15",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 54,
    name: "Friggfeltet",
    homePageLink: "http://cms.frigg.no/?cat=94",
    openingTime: null,
    closingTime: null,
    locationId: 41,
    location: {
      id: 41,
      latitude: "59.934170449326",
      longitude: "10.711911380796",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0371",
      address: "Apalveien 8",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 55,
    name: "Frogner stadion",
    homePageLink: "http://osk.idrettenonline.no/p/15537/hovedside",
    openingTime: null,
    closingTime: null,
    locationId: 42,
    location: {
      id: 42,
      latitude: "59.926991077431",
      longitude: "10.709394287554",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0368",
      address: "Middelthuns gate 26",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 56,
    name: "Frogner tennis",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 43,
    location: {
      id: 43,
      latitude: null,
      longitude: null,
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0368",
      address: "Kirkeveien 20",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 57,
    name: "Frognerborgen",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 44,
    location: {
      id: 44,
      latitude: "59.924337",
      longitude: "10.706635",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0268",
      address: "Frognerborgen lekeplass",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 58,
    name: "Frognerkilen skatepark",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 45,
    location: {
      id: 45,
      latitude: "59.917905",
      longitude: "10.688678",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0273",
      address: "Frognerkilen",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 59,
    name: "Furuset aktivitetspark",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 46,
    location: {
      id: 46,
      latitude: "59.940283694616",
      longitude: "10.895565222867",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1051",
      address: "Søren Bulls vei 4",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 60,
    name: "Furuset idrettshall",
    homePageLink: "https://www.hbbk.no/",
    openingTime: null,
    closingTime: null,
    locationId: 47,
    location: {
      id: 47,
      latitude: "59.94173",
      longitude: "10.897701",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1051",
      address: "Trygve Lies Plass 1",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 61,
    name: "Furuset idrettspark",
    homePageLink:
      "http://kxweb.no/portal/theme/organization/main.do?siteId=171",
    openingTime: null,
    closingTime: null,
    locationId: 48,
    location: {
      id: 48,
      latitude: "59.933847292059",
      longitude: "10.873128538696",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1081",
      address: "Strømsveien 303",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 62,
    name: "Furuset parkourpark",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 49,
    location: {
      id: 49,
      latitude: "59.944914",
      longitude: "10.896493",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1053",
      address: "Verdensparken",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 63,
    name: "Fyrstikkalleen idrettshall",
    homePageLink:
      "http://kxweb.no/portal/theme/organization/main.do;jsessionid=CBDA688584B1A47B976F6E47CF815CB9?siteId=145",
    openingTime: null,
    closingTime: null,
    locationId: 50,
    location: {
      id: 50,
      latitude: "59.915255473376",
      longitude: "10.794325204854",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0661",
      address: "Fyrstikkalleen 21",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 64,
    name: "Granern",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 51,
    location: {
      id: 51,
      latitude: "59.935749",
      longitude: "10.816634",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0583",
      address: "Nordalveien 43",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 65,
    name: "Grefsen stadion",
    homePageLink: "http://www.kjelsaas.no/",
    openingTime: null,
    closingTime: null,
    locationId: 52,
    location: {
      id: 52,
      latitude: null,
      longitude: null,
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0493",
      address: "Neptunveien 8",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 66,
    name: "Greibanen",
    homePageLink: "http://www.grei.no/",
    openingTime: null,
    closingTime: null,
    locationId: 53,
    location: {
      id: 53,
      latitude: "59.957683",
      longitude: "10.861239",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0956",
      address: "Greibanen",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 67,
    name: "Gressbanen Ready",
    homePageLink: "http://ready.no/",
    openingTime: null,
    closingTime: null,
    locationId: 54,
    location: {
      id: 54,
      latitude: "59.951475792736",
      longitude: "10.675666818001",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0773",
      address: "Stasjonsveien 24",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 68,
    name: "Grorud idrettspark",
    homePageLink: "http://grorud-il.no/",
    openingTime: null,
    closingTime: null,
    locationId: 55,
    location: {
      id: 55,
      latitude: "59.958630533163",
      longitude: "10.882408240739",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0952",
      address: "Grorudveien 5",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 69,
    name: "Groruddalen golfbane",
    homePageLink: "http://www.grorudgk.no/",
    openingTime: null,
    closingTime: null,
    locationId: 56,
    location: {
      id: 56,
      latitude: "59.96869530374",
      longitude: "10.916984631013",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0988",
      address: "Karen Platous vei 33",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 70,
    name: "Groruddalen gymsal",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 57,
    location: {
      id: 57,
      latitude: "59.954859191536",
      longitude: "10.888623548789",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0776",
      address: "Vestbyveien 13",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 71,
    name: "Grünerhagen",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 58,
    location: {
      id: 58,
      latitude: "59.922462",
      longitude: "10.755084",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0551",
      address: "Grünerhagen",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 72,
    name: "Grünerhallen",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 59,
    location: {
      id: 59,
      latitude: "59.926934",
      longitude: "10.765048",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0552",
      address: "Seilduksgata 30",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 73,
    name: "Hallager idrettspark",
    homePageLink: "http://www.nordstrand-if.no/",
    openingTime: null,
    closingTime: null,
    locationId: 60,
    location: {
      id: 60,
      latitude: "59.841856642729",
      longitude: "10.78184195385",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1168",
      address: "Herregårdsveien 40",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 74,
    name: "Harald Hals plass",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 61,
    location: {
      id: 61,
      latitude: "59.944546",
      longitude: "10.734709",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0854",
      address: "Harald Hals plass",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 75,
    name: "Haraløkka idrettspark",
    homePageLink: "http://www.boelerif.no",
    openingTime: null,
    closingTime: null,
    locationId: 62,
    location: {
      id: 62,
      latitude: "59.883898",
      longitude: "10.857677",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0688",
      address: "Bølerlia",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 76,
    name: "Hasle kunstgressbane",
    homePageLink: "http://www.yourvismawebsite.com/lille-toyen-fotballklubb",
    openingTime: null,
    closingTime: null,
    locationId: 63,
    location: {
      id: 63,
      latitude: "59.921734550398",
      longitude: "10.790112987739",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0576",
      address: "Haralds vei 1",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 77,
    name: "Haugenstua idrettshall",
    homePageLink: "http://www.rommensk.no/",
    openingTime: null,
    closingTime: null,
    locationId: 64,
    location: {
      id: 64,
      latitude: "59.954566",
      longitude: "10.920424",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0982",
      address: "Smiuveien 257",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 78,
    name: "Haugerud idrettshall",
    homePageLink: "http://www.haugerudif.no/",
    openingTime: null,
    closingTime: null,
    locationId: 65,
    location: {
      id: 65,
      latitude: "59.923027866329",
      longitude: "10.858276934555",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0673",
      address: "Tvetenveien 181",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 79,
    name: "Haugerud idrettspark",
    homePageLink: "http://www.haugerudif.no/",
    openingTime: null,
    closingTime: null,
    locationId: 66,
    location: {
      id: 66,
      latitude: "59.922517877992",
      longitude: "10.859411340611",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0673",
      address: "Tvetenveien 183",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 80,
    name: "Haugerud judo",
    homePageLink: "http://www.njjk.no/",
    openingTime: null,
    closingTime: null,
    locationId: 67,
    location: {
      id: 67,
      latitude: "59.923027866329",
      longitude: "10.858276934555",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0673",
      address: "Tvetenveien 181",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 81,
    name: "Holmlia aktivitetsløype",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 68,
    location: {
      id: 68,
      latitude: "59.836194",
      longitude: "10.794258",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1255",
      address: "Holmlia aktivitetsløype",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 82,
    name: "Holmlia idrettshall",
    homePageLink: "http://www.holmliasport.no",
    openingTime: null,
    closingTime: null,
    locationId: 69,
    location: {
      id: 69,
      latitude: "59.833279",
      longitude: "10.790113",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1251",
      address: "Nordåsveien 3",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 83,
    name: "Holmlia idrettspark",
    homePageLink: "http://www.holmliasport.no/",
    openingTime: null,
    closingTime: null,
    locationId: 70,
    location: {
      id: 70,
      latitude: "59.8323998236",
      longitude: "10.789062440005",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1251",
      address: "Nordåsveien 1",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 84,
    name: "Holmlia PressPlay",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 71,
    location: {
      id: 71,
      latitude: "59.834535",
      longitude: "10.788331",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1254",
      address: "Holmlia PressPlay",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 85,
    name: "Hovseter idrettshall",
    homePageLink: "http://www.ullern.no/",
    openingTime: null,
    closingTime: null,
    locationId: 72,
    location: {
      id: 72,
      latitude: "59.949738721475",
      longitude: "10.654612443115",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0768",
      address: "Hovseterveien 74/76",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 86,
    name: "Høyenhallen",
    homePageLink:
      "http://tunetibk.no/portal/theme/organization/main.do?siteId=381",
    openingTime: null,
    closingTime: null,
    locationId: 73,
    location: {
      id: 73,
      latitude: "59.900016152812",
      longitude: "10.812526020125",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0678",
      address: "Traktorveien 15",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 87,
    name: "Idioten",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 74,
    location: {
      id: 74,
      latitude: "59.931145236757",
      longitude: "10.737235699499",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0454",
      address: "Pavels&#039; gate",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 88,
    name: "Jesperudjordet",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 75,
    location: {
      id: 75,
      latitude: "59.962722",
      longitude: "10.928088",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0985",
      address: "Jesperudjordet",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 89,
    name: "Jordal Amfi",
    homePageLink:
      "https://www.oslo.kommune.no/etater-foretak-og-ombud/kultur-og-idrettsbygg-oslo-kf/ferdigstilte-kultur-og-idrettsbyggprosjekter/jordal-amfi/",
    openingTime: null,
    closingTime: null,
    locationId: 76,
    location: {
      id: 76,
      latitude: "59.909236303514",
      longitude: "10.781857307392",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0657",
      address: "Jordalgata 12",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 90,
    name: "Jordal idrettshall",
    homePageLink:
      "http://www.vifhandball.no/portal/theme/organization/main.do?siteId=148",
    openingTime: null,
    closingTime: null,
    locationId: 77,
    location: {
      id: 77,
      latitude: "59.909502",
      longitude: "10.782062",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0657",
      address: "Jordalgata 12a",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 91,
    name: "Jordal idrettspark",
    homePageLink:
      "https://www.oslo.kommune.no/etater-foretak-og-ombud/kultur-og-idrettsbygg-oslo-kf/ferdigstilte-kultur-og-idrettsbyggprosjekter/jordal-amfi/",
    openingTime: null,
    closingTime: null,
    locationId: 78,
    location: {
      id: 78,
      latitude: "59.909561",
      longitude: "10.782105",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0657",
      address: "Jordalgata 1",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 92,
    name: "Jordal skatepark",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 79,
    location: {
      id: 79,
      latitude: "59.909295",
      longitude: "10.784535",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0657",
      address: "Jordalgata 1",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 93,
    name: "Jordal ungdomshall",
    homePageLink:
      "http://kxweb.no/portal/theme/organization/main.do?siteId=189&amp;setSportId=-1",
    openingTime: null,
    closingTime: null,
    locationId: 80,
    location: {
      id: 80,
      latitude: "59.909236303514",
      longitude: "10.781857307392",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0657",
      address: "Jordalgata 12",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 94,
    name: "Kalbakken treningshall",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 81,
    location: {
      id: 81,
      latitude: "59.951040649895",
      longitude: "10.873597423937",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0952",
      address: "Gårdsveien 6",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 95,
    name: "Kastellet idrettshall",
    homePageLink: "http://www.oslovolley.org/",
    openingTime: null,
    closingTime: null,
    locationId: 82,
    location: {
      id: 82,
      latitude: "59.873474625323",
      longitude: "10.7922338067",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1176",
      address: "Birger Olivers vei 34",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 96,
    name: "Kjelsås idrettshall",
    homePageLink: "http://www.kjelsaas.no/",
    openingTime: null,
    closingTime: null,
    locationId: 83,
    location: {
      id: 83,
      latitude: "59.965443562826",
      longitude: "10.785108621519",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0494",
      address: "Asbjørnsens vei 3",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 97,
    name: "Klemetsrud idrettshall",
    homePageLink:
      "http://idrett.speaker.no/organisation.asp?OrgElementId=20814",
    openingTime: null,
    closingTime: null,
    locationId: 84,
    location: {
      id: 84,
      latitude: "59.848419469851",
      longitude: "10.829194841654",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1281",
      address: "Lofsrudveien 6",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 98,
    name: "Kollbanen",
    homePageLink: "http://www.koll.no/",
    openingTime: null,
    closingTime: null,
    locationId: 85,
    location: {
      id: 85,
      latitude: "59.965395",
      longitude: "10.740687",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0862",
      address: "Minister Ditleffs Vei",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 99,
    name: "Korsvoll idrettspark",
    homePageLink: "http://www.korsvollil.no/",
    openingTime: null,
    closingTime: null,
    locationId: 86,
    location: {
      id: 86,
      latitude: "59.961512392132",
      longitude: "10.757474144173",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0880",
      address: "Langåsveien 18",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 100,
    name: "Krakabøla lekeplass",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 87,
    location: {
      id: 87,
      latitude: "59.90574",
      longitude: "10.769912",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0192",
      address: "St. Halvards gate 23",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 101,
    name: "Kringsjå idrettshall",
    homePageLink: "http://www.koll.no/",
    openingTime: null,
    closingTime: null,
    locationId: 88,
    location: {
      id: 88,
      latitude: "59.962830104714",
      longitude: "10.73253827451",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0864",
      address: "Sognsveien 210 c",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 102,
    name: "Kringsjå idrettspark",
    homePageLink: "http://www.lyn.no/",
    openingTime: null,
    closingTime: null,
    locationId: 89,
    location: {
      id: 89,
      latitude: "59.964797804048",
      longitude: "10.727134473893",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0864",
      address: "Olav M. Troviks vei 13",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 103,
    name: "Kristparken",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 90,
    location: {
      id: 90,
      latitude: "59.917692",
      longitude: "10.748501",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0178",
      address: "Deichmans gate 10C",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 104,
    name: "Kubaparken",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 91,
    location: {
      id: 91,
      latitude: "59.924853",
      longitude: "10.752573",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0175",
      address: "Kuba park",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 105,
    name: "Lambertseter idrettspark",
    homePageLink: "http://www.lambertseterif.no/",
    openingTime: null,
    closingTime: null,
    locationId: 92,
    location: {
      id: 92,
      latitude: "59.871776",
      longitude: "10.820658",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1155",
      address: "Feltspatveien",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 106,
    name: "Lille Bislett",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 93,
    location: {
      id: 93,
      latitude: "59.923350533298",
      longitude: "10.734048619623",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0170",
      address: "Dalsbergstien 17",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 107,
    name: "Lindebergparken",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 94,
    location: {
      id: 94,
      latitude: "59.929884",
      longitude: "10.876255",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1069",
      address: "Lindebergveien 9",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 108,
    name: "Linderud idrettshall",
    homePageLink: "http://www.linderudil.no/",
    openingTime: null,
    closingTime: null,
    locationId: 95,
    location: {
      id: 95,
      latitude: "59.94123",
      longitude: "10.83645",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0594",
      address: "Statsråd Mathisens vei 25",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 109,
    name: "Lunden park",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 96,
    location: {
      id: 96,
      latitude: "59.942045",
      longitude: "10.82512",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0598",
      address: "Brobekkveien 22-22",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 110,
    name: "Løren idrettspark",
    homePageLink: "http://www.hasle-loren.no/",
    openingTime: null,
    closingTime: null,
    locationId: 97,
    location: {
      id: 97,
      latitude: "59.935470846648",
      longitude: "10.8050105514",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0580",
      address: "Spireaveien 3",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 111,
    name: "Løren ishall",
    homePageLink: "http://www.hasle-loren.no/",
    openingTime: null,
    closingTime: null,
    locationId: 98,
    location: {
      id: 98,
      latitude: "59.935991",
      longitude: "10.804972",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0580",
      address: "Spireaveien 1",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 112,
    name: "Manglerud idrettspark",
    homePageLink: "http://msfotball.no/",
    openingTime: null,
    closingTime: null,
    locationId: 99,
    location: {
      id: 99,
      latitude: "59.894207342103",
      longitude: "10.824593841509",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0681",
      address: "Plogveien 24",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 113,
    name: "Manglerud ishall",
    homePageLink: "http://www.mshockey.no/",
    openingTime: null,
    closingTime: null,
    locationId: 100,
    location: {
      id: 100,
      latitude: "59.894207342103",
      longitude: "10.824593841509",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0681",
      address: "Plogveien 24",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 114,
    name: "Marienlyst idrettshall",
    homePageLink: "http://www.bisletbasket.no/",
    openingTime: null,
    closingTime: null,
    locationId: 101,
    location: {
      id: 101,
      latitude: null,
      longitude: null,
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0361",
      address: "Tusentrippen 5",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 115,
    name: "Marienlystparken",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 102,
    location: {
      id: 102,
      latitude: "59.934233",
      longitude: "10.724534",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0361",
      address: "Marienlystparken",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 116,
    name: "Mortensrud idrettspark",
    homePageLink: "http://www.klemetsrud-il.no/",
    openingTime: null,
    closingTime: null,
    locationId: 103,
    location: {
      id: 103,
      latitude: "59.846213",
      longitude: "10.829802",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1281",
      address: "Lofsrudveien",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 117,
    name: "Muselunden",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 104,
    location: {
      id: 104,
      latitude: "59.939669",
      longitude: "10.785082",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0582",
      address: "Muselunden",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 118,
    name: "Nedre Foss park",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 105,
    location: {
      id: 105,
      latitude: "59.922756",
      longitude: "10.753557",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0551",
      address: "Nedre Foss park lekeplass",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 119,
    name: "Nordre Åsen idrettspark",
    homePageLink: "http://www.skeid.no/",
    openingTime: null,
    closingTime: null,
    locationId: 106,
    location: {
      id: 106,
      latitude: "59.942768456912",
      longitude: "10.784873924011",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0488",
      address: "Kjelsåsveien 7",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 120,
    name: "Olafiaplassen streetskateanlegg",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 107,
    location: {
      id: 107,
      latitude: "59.913893",
      longitude: "10.758877",
      country: null,
      city: null,
      area: null,
      postalCode: null,
      address: null,
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 121,
    name: "Operaallmenningen kunstisbane",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 108,
    location: {
      id: 108,
      latitude: "59.9086861",
      longitude: "10.7521245",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0150",
      address: "Anne Cath Vestlys plass",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 122,
    name: "Oppsal arena",
    homePageLink: "http://www.oppsalif.no/",
    openingTime: null,
    closingTime: null,
    locationId: 109,
    location: {
      id: 109,
      latitude: "59.905798600769",
      longitude: "10.846298531059",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0671",
      address: "Vetlandsveien 49",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 123,
    name: "Oslo skatehall",
    homePageLink: "http://www.osloskatehall.no",
    openingTime: null,
    closingTime: null,
    locationId: 110,
    location: {
      id: 110,
      latitude: "59.941987313705",
      longitude: "10.75338302729",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0467",
      address: "Stavangergata 28",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 124,
    name: "Paulus&#039; plass",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 111,
    location: {
      id: 111,
      latitude: "59.926157",
      longitude: "10.758294",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0554",
      address: "Paulus&#039; plass",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 125,
    name: "Persbråten idrettshall",
    homePageLink: "http://www.pbbk.no/",
    openingTime: null,
    closingTime: null,
    locationId: 112,
    location: {
      id: 112,
      latitude: "59.945350960145",
      longitude: "10.657866849557",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0768",
      address: "Gamle Hovsetervei 1",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 126,
    name: "Prinsdal idrettspark",
    homePageLink: "http://www.hauketoif.no",
    openingTime: null,
    closingTime: null,
    locationId: 113,
    location: {
      id: 113,
      latitude: "59.833611",
      longitude: "10.815103",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1263",
      address: "Øvre Prinsdals vei 62",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 127,
    name: "Rommen flerbrukshall",
    homePageLink: "http://sveiva.no/",
    openingTime: null,
    closingTime: null,
    locationId: 114,
    location: {
      id: 114,
      latitude: "59.967367334413",
      longitude: "10.914417596982",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0988",
      address: "Karen Platous vei 31",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 128,
    name: "Romsås idrettshall",
    homePageLink: "http://www.romsas-il.no/",
    openingTime: null,
    closingTime: null,
    locationId: 115,
    location: {
      id: 115,
      latitude: "59.970834328422",
      longitude: "10.900122476151",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1281",
      address: "Sverre Iversens vei 37",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 129,
    name: "Rudolf Nilsens plass",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 116,
    location: {
      id: 116,
      latitude: "59.916446",
      longitude: "10.765457",
      country: null,
      city: null,
      area: null,
      postalCode: null,
      address: null,
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 130,
    name: "Rustad idrettspark",
    homePageLink: "http://www.rustad-idrettslag.no/",
    openingTime: null,
    closingTime: null,
    locationId: 117,
    location: {
      id: 117,
      latitude: "59.873472",
      longitude: "10.83773",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0692",
      address: "Paal Bergs vei 135",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 131,
    name: "Røa idrettspark",
    homePageLink: "http://www.roail.no/",
    openingTime: null,
    closingTime: null,
    locationId: 118,
    location: {
      id: 118,
      latitude: "59.94301300551",
      longitude: "10.635069254917",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0760",
      address: "Kristian Auberts vei 20",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 132,
    name: "Schous plass",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 119,
    location: {
      id: 119,
      latitude: "59.920816",
      longitude: "10.760331",
      country: null,
      city: null,
      area: null,
      postalCode: null,
      address: null,
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 133,
    name: "Olaf Bulls plass",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 120,
    location: {
      id: 120,
      latitude: "59.912626",
      longitude: "10.711247",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0270",
      address: "Drammensveien 60",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 134,
    name: "Skur 13",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 121,
    location: {
      id: 121,
      latitude: "59.909427",
      longitude: "10.721666",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0250",
      address: "Filipstadveien 3",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 135,
    name: "Skøyen idrettshall",
    homePageLink:
      "http://idrett.speaker.no/organisation.asp?OrgElementId=20721",
    openingTime: null,
    closingTime: null,
    locationId: 122,
    location: {
      id: 122,
      latitude: "59.929056522357",
      longitude: "10.690604555759",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0375",
      address: "Monolitveien 6",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 136,
    name: "Snippen lekepark",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 123,
    location: {
      id: 123,
      latitude: "59.915834",
      longitude: "10.77011",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0578",
      address: "Snippen lekepark",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 137,
    name: "Sofienbergparken",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 124,
    location: {
      id: 124,
      latitude: "59.921204963926",
      longitude: "10.76700925827",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0558",
      address: "Sofienbergparken",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 138,
    name: "Sommerfrydhagen",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 125,
    location: {
      id: 125,
      latitude: "59.911838",
      longitude: "10.776385",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0652",
      address: "Sverres gate 22",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 139,
    name: "Sonja Henie ishall",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 126,
    location: {
      id: 126,
      latitude: "59.927820598293",
      longitude: "10.709264498679",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0368",
      address: "Middelthunsgate 26",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 140,
    name: "Spikersuppa",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 127,
    location: {
      id: 127,
      latitude: "59.913855",
      longitude: "10.737218",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0162",
      address: "Spikersuppa",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 141,
    name: "St. Hanshaugen",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 128,
    location: {
      id: 128,
      latitude: "59.927066",
      longitude: "10.74154",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0171",
      address: "Sankt Hanshaugen",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 142,
    name: "Stensparken",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 129,
    location: {
      id: 129,
      latitude: "59.928734",
      longitude: "10.730374",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0354",
      address: "Stensparken",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 143,
    name: "Stovner idrettshall",
    homePageLink: "https://www.stovnersk.no/",
    openingTime: null,
    closingTime: null,
    locationId: 130,
    location: {
      id: 130,
      latitude: "59.960945680487",
      longitude: "10.927964824971",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "",
      address: "Stovner senter 40",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 144,
    name: "Sverre Refstad plass",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 131,
    location: {
      id: 131,
      latitude: "59.933740047866",
      longitude: "10.821215296443",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0583",
      address: "Midtveien 17E",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 145,
    name: "Teglverkshallen",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 132,
    location: {
      id: 132,
      latitude: "59.923984",
      longitude: "10.795313",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0579",
      address: "Grensesvingen 60",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 146,
    name: "Tinker&#039;n (Framneshaven)",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 133,
    location: {
      id: 133,
      latitude: "59.911509",
      longitude: "10.711148",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0301",
      address: "Framnesveien",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 147,
    name: "Tonsenhagen skoleidrettsplass",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 134,
    location: {
      id: 134,
      latitude: "59.947023",
      longitude: "10.828818",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0592",
      address: "Anna Rogstads vei 14",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 148,
    name: "Tøyen parkourpark",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 135,
    location: {
      id: 135,
      latitude: "59.915219",
      longitude: "10.775385",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0578",
      address: "Tøyen parkourpark",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 149,
    name: "Tåsen skole idrettshall",
    homePageLink: "http://www.kollvolley.no/",
    openingTime: null,
    closingTime: null,
    locationId: 136,
    location: {
      id: 136,
      latitude: "59.953170491499",
      longitude: "10.751459653955",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0875",
      address: "Nordbergveien 15",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 150,
    name: "Ullern idrettspark",
    homePageLink: "http://www.ullern.no/",
    openingTime: null,
    closingTime: null,
    locationId: 137,
    location: {
      id: 137,
      latitude: "59.927295",
      longitude: "10.632429",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0382",
      address: "Myntfunnveien 3",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 151,
    name: "Vahl flerbrukshall",
    homePageLink: "http://nb-no.facebook.com/oslobasketballklubb/",
    openingTime: null,
    closingTime: null,
    locationId: 138,
    location: {
      id: 138,
      latitude: "59.916462498637",
      longitude: "10.763985126614",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0187",
      address: "Vahls gate 4",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 152,
    name: "Valle Hovin idrettspark",
    homePageLink: "http://www.vif-fotball.no/",
    openingTime: null,
    closingTime: null,
    locationId: 139,
    location: {
      id: 139,
      latitude: "59.920243698817",
      longitude: "10.805256783212",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0663",
      address: "Innspurten 16",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 153,
    name: "Valle Hovin stadion (midlertidig stengt)",
    homePageLink: "https://www.facebook.com/vallehovinstadion/",
    openingTime: null,
    closingTime: null,
    locationId: 140,
    location: {
      id: 140,
      latitude: "59.918434",
      longitude: "10.804571",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0663",
      address: "Innspurten 1",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 154,
    name: "Verdensparken",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 141,
    location: {
      id: 141,
      latitude: "59.943119",
      longitude: "10.895277",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "1053",
      address: "Søren Bulls vei 4",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 155,
    name: "Amaldus Nielsens plass (Vestkanttorget)",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 142,
    location: {
      id: 142,
      latitude: "59.92423",
      longitude: "10.713592",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0260",
      address: "Professor Dahls gate",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 156,
    name: "Voksen fleridrettshall",
    homePageLink:
      "http://www.kxweb.no/portal/theme/organization/main.do?siteId=117&amp;setSportId=-1",
    openingTime: null,
    closingTime: null,
    locationId: 143,
    location: {
      id: 143,
      latitude: "59.954996974725",
      longitude: "10.655132473261",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0771",
      address: "Jarbakken 1",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 157,
    name: "Voldsløkka idrettspark",
    homePageLink: "http://sageneif.no/",
    openingTime: null,
    closingTime: null,
    locationId: 144,
    location: {
      id: 144,
      latitude: "59.944037",
      longitude: "10.75584",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0467",
      address: "Stavangergata 40",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 158,
    name: "Vulkan flerbrukshall",
    homePageLink: "http://www.centrumtigers.com/",
    openingTime: null,
    closingTime: null,
    locationId: 145,
    location: {
      id: 145,
      latitude: "59.922956",
      longitude: "10.751952",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0175",
      address: "Maridalsveien 17",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 159,
    name: "Wilsters vei",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 146,
    location: {
      id: 146,
      latitude: "59.933166488319",
      longitude: "10.809967975407",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0580",
      address: "Wilsters vei 3",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 160,
    name: "Øraker idrettshall",
    homePageLink: "http://www.ullern.no/",
    openingTime: null,
    closingTime: null,
    locationId: 147,
    location: {
      id: 147,
      latitude: "59.925452",
      longitude: "10.637839",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0284",
      address: "Lilleakerveien 60",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 161,
    name: "Øvre Foss kunstgressbane",
    homePageLink: null,
    openingTime: null,
    closingTime: null,
    locationId: 148,
    location: {
      id: 148,
      latitude: "59.929553",
      longitude: "10.75707",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "0459",
      address: "Mølleparken 6",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
  {
    id: 162,
    name: "Årvoll idrettspark",
    homePageLink: "http://www.aarvoll.no/",
    openingTime: null,
    closingTime: null,
    locationId: 149,
    location: {
      id: 149,
      latitude: "59.944664139781",
      longitude: "10.81419326723",
      country: "Norway",
      city: "Oslo",
      area: "Oslo",
      postalCode: "",
      address: "Bård Skolemesters vei 1",
    },
    events: null,
    activities: null,
    activeGurus: null,
  },
];
